// Generated by cbindgen

#ifndef MIDEN_SWIFT_CLIENT_H
#define MIDEN_SWIFT_CLIENT_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of pending requests in the worker queue
 * Prevents unbounded memory growth if caller spams requests
 */
#define WORKER_QUEUE_CAPACITY 256

/**
 * Error: invalid parameter
 */
#define ERR_INVALID_PARAM -1

/**
 * Error: invalid handle or worker closed
 */
#define ERR_INVALID_HANDLE -2

/**
 * Error: account/key operation failed
 */
#define ERR_ACCOUNT_OP -3

/**
 * Error: note operation failed
 */
#define ERR_NOTE_OP -4

/**
 * Error: balance/account lookup failed
 */
#define ERR_LOOKUP -5

/**
 * Error: transaction submission failed
 */
#define ERR_TX_SUBMIT -6

/**
 * Error: worker queue is full
 */
#define ERR_QUEUE_FULL -8

/**
 * Error: operation timed out
 */
#define ERR_TIMEOUT -99

/**
 * Handle structure containing sender to worker thread
 */
typedef struct MidenWorkerHandle MidenWorkerHandle;

/**
 * Opaque handle type for FFI
 */
typedef struct MidenWorkerHandle *MidenHandle;

/**
 * Callback for sync operation: (user_data, error_code, block_num)
 */
typedef void (*SyncCallback)(void*, int32_t, uint32_t);

/**
 * Callback for create wallet operation: (user_data, error_code, account_id_ptr, account_id_len)
 */
typedef void (*CreateWalletCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for get accounts operation: (user_data, error_code, json_ptr, json_len)
 */
typedef void (*GetAccountsCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for get balance operation: (user_data, error_code, json_ptr, json_len)
 */
typedef void (*GetBalanceCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for test connection operation: (user_data, error_code)
 */
typedef void (*TestConnectionCallback)(void*, int32_t);

/**
 * Callback for get input notes operation: (user_data, error_code, json_ptr, json_len)
 */
typedef void (*GetInputNotesCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for consume notes operation: (user_data, error_code, tx_id_ptr, tx_id_len)
 */
typedef void (*ConsumeNotesCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Free bytes allocated by Rust (for async callback results)
 *
 * MUST be called to release memory returned by async callbacks.
 * The (ptr, len) pair must match exactly what was returned by the callback.
 */
void wc_bytes_free(uint8_t *ptr, uintptr_t len);

/**
 * Create and initialize Miden Client
 *
 * This starts a dedicated worker thread that owns the MidenClient.
 * All operations are sent to this worker thread via channels.
 *
 * # Parameters
 * - `keystore_path`: Keystore storage directory path (C string)
 * - `store_path`: SQLite database file path (C string)
 * - `rpc_endpoint`: RPC endpoint URL (C string, can be NULL to use testnet)
 * - `handle_out`: Output client handle
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Initialization failed
 */
int32_t wc_miden_create(const char *keystore_path,
                        const char *store_path,
                        const char *rpc_endpoint,
                        MidenHandle *handle_out);

/**
 * Destroy client and release resources
 *
 * Sends shutdown signal to worker thread and waits for it to finish.
 * Safe to call multiple times - the handle pointer is set to NULL after destruction.
 *
 * # Parameters
 * - `handle_ptr`: Pointer to the handle (will be set to NULL after destruction)
 *
 * # Example (Swift)
 * ```swift
 * var handle: MidenHandle? = ...
 * wc_miden_destroy(&handle)  // handle is now nil
 * ```
 *
 * # Shutdown Semantics
 * This performs a **fast shutdown**: pending requests in the queue will be dropped.
 * Callbacks for in-flight async operations may not be invoked.
 * If you need graceful shutdown (process all pending requests), do not use this pattern.
 */
void wc_miden_destroy(MidenHandle *handle_ptr);

/**
 * Sync state (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 * Use wc_miden_sync_async for non-blocking operation.
 *
 * NOTE: Timeout (-99) only abandons waiting; the operation may still complete in background.
 *
 * # Returns
 * - 0: Success
 * - -2: Invalid handle or worker closed
 * - -8: Queue full
 * - -99: Operation timed out
 */
int32_t wc_miden_sync(MidenHandle handle, uint32_t *block_num_out);

/**
 * Create a new wallet account (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 */
int32_t wc_miden_create_wallet(MidenHandle handle,
                               const uint8_t *seed_ptr,
                               uintptr_t seed_len,
                               uint8_t *account_id_out,
                               uintptr_t *account_id_out_len);

/**
 * Get all accounts (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 */
int32_t wc_miden_get_accounts(MidenHandle handle,
                              uint8_t *accounts_json_out,
                              uintptr_t *accounts_json_out_len);

/**
 * Get account balance (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 */
int32_t wc_miden_get_balance(MidenHandle handle,
                             const char *account_id_hex,
                             uint8_t *balance_json_out,
                             uintptr_t *balance_json_out_len);

/**
 * Test connection (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 */
int32_t wc_miden_test_connection(MidenHandle handle);

/**
 * Get consumable input notes (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 */
int32_t wc_miden_get_input_notes(MidenHandle handle,
                                 const char *account_id_hex,
                                 uint8_t *notes_json_out,
                                 uintptr_t *notes_json_out_len);

/**
 * Consume notes (blocking)
 *
 * WARNING: This is a blocking call. Do NOT call from the main/UI thread.
 * NOTE: Timeout (-99) only abandons waiting; the transaction may still be submitted.
 */
int32_t wc_miden_consume_notes(MidenHandle handle,
                               const char *account_id_hex,
                               const char *note_ids_json,
                               uint8_t *tx_id_out,
                               uintptr_t *tx_id_out_len);

/**
 * Sync state (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 * Swift callers should dispatch to main queue if updating UI.
 */
int32_t wc_miden_sync_async(MidenHandle handle, SyncCallback callback, void *user_data);

/**
 * Create wallet (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 */
int32_t wc_miden_create_wallet_async(MidenHandle handle,
                                     const uint8_t *seed_ptr,
                                     uintptr_t seed_len,
                                     CreateWalletCallback callback,
                                     void *user_data);

/**
 * Get accounts (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 */
int32_t wc_miden_get_accounts_async(MidenHandle handle,
                                    GetAccountsCallback callback,
                                    void *user_data);

/**
 * Get balance (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 */
int32_t wc_miden_get_balance_async(MidenHandle handle,
                                   const char *account_id_hex,
                                   GetBalanceCallback callback,
                                   void *user_data);

/**
 * Test connection (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 */
int32_t wc_miden_test_connection_async(MidenHandle handle,
                                       TestConnectionCallback callback,
                                       void *user_data);

/**
 * Get input notes (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 */
int32_t wc_miden_get_input_notes_async(MidenHandle handle,
                                       const char *account_id_hex,
                                       GetInputNotesCallback callback,
                                       void *user_data);

/**
 * Consume notes (async)
 *
 * NOTE: Callback is invoked on worker thread, NOT main thread.
 */
int32_t wc_miden_consume_notes_async(MidenHandle handle,
                                     const char *account_id_hex,
                                     const char *note_ids_json,
                                     ConsumeNotesCallback callback,
                                     void *user_data);

/**
 * Keccak256 hash function
 *
 * # Parameters
 * - `data_ptr`: Input data pointer
 * - `data_len`: Input data length
 * - `out_ptr`: Output buffer pointer (must be at least 32 bytes)
 * - `out_len`: Input: buffer capacity; Output: actual length (32)
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters or buffer too small
 */
int32_t wc_keccak256(const uint8_t *data_ptr,
                     uintptr_t data_len,
                     uint8_t *out_ptr,
                     uintptr_t *out_len);

/**
 * Convert account ID bytes to hex string
 */
int32_t wc_miden_account_id_to_hex(const uint8_t *account_id_ptr,
                                   uintptr_t account_id_len,
                                   uint8_t *hex_out,
                                   uintptr_t *hex_out_len);

#endif  /* MIDEN_SWIFT_CLIENT_H */
