// Generated by cbindgen

#ifndef MIDEN_SWIFT_CLIENT_H
#define MIDEN_SWIFT_CLIENT_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Arc_Mutex_MidenContext Arc_Mutex_MidenContext;

/**
 * Opaque handle type
 * Points to Arc<Mutex<MidenContext>> for thread-safe access
 */
typedef struct Arc_Mutex_MidenContext *MidenHandle;

/**
 * Callback for sync operation: (user_data, error_code, block_num)
 */
typedef void (*SyncCallback)(void*, int32_t, uint32_t);

/**
 * Callback for test connection operation: (user_data, error_code)
 */
typedef void (*TestConnectionCallback)(void*, int32_t);

/**
 * Callback for create wallet operation: (user_data, error_code, account_id_ptr, account_id_len)
 * Note: Swift must call wc_bytes_free(ptr, len) to free the returned data
 */
typedef void (*CreateWalletCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for get accounts operation: (user_data, error_code, json_ptr, json_len)
 * Note: Swift must call wc_bytes_free(ptr, len) to free the returned data
 */
typedef void (*GetAccountsCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for get balance operation: (user_data, error_code, json_ptr, json_len)
 * Note: Swift must call wc_bytes_free(ptr, len) to free the returned data
 */
typedef void (*GetBalanceCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for get input notes operation: (user_data, error_code, json_ptr, json_len)
 * Note: Swift must call wc_bytes_free(ptr, len) to free the returned data
 */
typedef void (*GetInputNotesCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Callback for consume notes operation: (user_data, error_code, tx_id_ptr, tx_id_len)
 * Note: Swift must call wc_bytes_free(ptr, len) to free the returned data
 */
typedef void (*ConsumeNotesCallback)(void*, int32_t, uint8_t*, uintptr_t);

/**
 * Free bytes allocated by Rust (for async callback results)
 *
 * Swift must call this to free data returned via async callbacks
 */
void wc_bytes_free(uint8_t *ptr, uintptr_t len);

/**
 * Create and initialize Miden Client
 *
 * # Parameters
 * - `keystore_path`: Keystore storage directory path (C string)
 * - `store_path`: SQLite database file path (C string)
 * - `rpc_endpoint`: RPC endpoint URL (C string, can be NULL to use testnet)
 * - `handle_out`: Output client handle
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Initialization failed
 *
 * # Note
 * The caller is responsible for calling `wc_miden_destroy` to release resources after use
 */
int32_t wc_miden_create(const char *keystore_path,
                        const char *store_path,
                        const char *rpc_endpoint,
                        MidenHandle *handle_out);

/**
 * Destroy client and release resources
 *
 * # Parameters
 * - `handle`: Client handle
 *
 * # Note
 * Must execute drop in Tokio runtime context, because SQLite connection pool's
 * SyncWrapper::drop needs to call spawn_blocking_background
 */
void wc_miden_destroy(MidenHandle handle);

/**
 * Sync state
 *
 * # Parameters
 * - `handle`: Client handle
 * - `block_num_out`: Output latest block number (can be NULL)
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid handle
 * - -2: Sync failed
 */
int32_t wc_miden_sync(MidenHandle handle, uint32_t *block_num_out);

/**
 * Async version of sync state
 *
 * # Parameters
 * - `handle`: Client handle
 * - `callback`: Callback function (user_data, error_code, block_num)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid handle or callback
 */
int32_t wc_miden_sync_async(MidenHandle handle, SyncCallback callback, void *user_data);

/**
 * Test Miden Client connection
 *
 * # Parameters
 * - `handle`: Client handle
 *
 * # Returns
 * - 0: Connection OK
 * - -1: Invalid handle
 * - -2: Connection failed
 */
int32_t wc_miden_test_connection(MidenHandle handle);

/**
 * Async version of test connection
 *
 * # Parameters
 * - `handle`: Client handle
 * - `callback`: Callback function (user_data, error_code)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid handle
 */
int32_t wc_miden_test_connection_async(MidenHandle handle,
                                       TestConnectionCallback callback,
                                       void *user_data);

/**
 * Create a new Miden wallet account
 *
 * # Parameters
 * - `handle`: Client handle
 * - `seed_ptr`: 32-byte random seed (if NULL, auto-generated)
 * - `seed_len`: Seed length (must be 32, ignored if seed_ptr is NULL)
 * - `account_id_out`: Output buffer for account ID (at least 64 bytes for hex string)
 * - `account_id_out_len`: Input as buffer size, output as actual length
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account creation failed
 */
int32_t wc_miden_create_wallet(MidenHandle handle,
                               const uint8_t *seed_ptr,
                               uintptr_t seed_len,
                               uint8_t *account_id_out,
                               uintptr_t *account_id_out_len);

/**
 * Async version of create wallet
 *
 * # Parameters
 * - `handle`: Client handle
 * - `seed_ptr`: 32-byte random seed (if NULL, auto-generated)
 * - `seed_len`: Seed length (must be 32, ignored if seed_ptr is NULL)
 * - `callback`: Callback function (user_data, error_code, account_id_ptr, account_id_len)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid parameters
 * - -2: Invalid handle
 */
int32_t wc_miden_create_wallet_async(MidenHandle handle,
                                     const uint8_t *seed_ptr,
                                     uintptr_t seed_len,
                                     CreateWalletCallback callback,
                                     void *user_data);

/**
 * Get all accounts list
 *
 * # Parameters
 * - `handle`: Client handle
 * - `accounts_json_out`: Output buffer for JSON-formatted account list
 * - `accounts_json_out_len`: Input as buffer size, output as actual length
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Get failed
 */
int32_t wc_miden_get_accounts(MidenHandle handle,
                              uint8_t *accounts_json_out,
                              uintptr_t *accounts_json_out_len);

/**
 * Async version of get accounts
 *
 * # Parameters
 * - `handle`: Client handle
 * - `callback`: Callback function (user_data, error_code, json_ptr, json_len)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid handle
 */
int32_t wc_miden_get_accounts_async(MidenHandle handle,
                                    GetAccountsCallback callback,
                                    void *user_data);

/**
 * Get account balance
 *
 * Returns JSON-formatted information about all assets in the account, including fungible and non-fungible assets.
 *
 * # Parameters
 * - `handle`: Client handle
 * - `account_id_hex`: Account ID (hex string, e.g., "0x...")
 * - `balance_json_out`: Output buffer for JSON-formatted balance information
 * - `balance_json_out_len`: Input as buffer size, output as actual length
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account ID parsing failed
 * - -4: Account not found
 * - -5: Get balance failed
 *
 * # JSON 输出格式
 * ```json
 * {
 *   "account_id": "0x...",
 *   "fungible_assets": [
 *     {"faucet_id": "0x...", "amount": 1000}
 *   ],
 *   "total_fungible_count": 1,
 *   "total_non_fungible_count": 0
 * }
 * ```
 */
int32_t wc_miden_get_balance(MidenHandle handle,
                             const char *account_id_hex,
                             uint8_t *balance_json_out,
                             uintptr_t *balance_json_out_len);

/**
 * Async version of get balance
 *
 * # Parameters
 * - `handle`: Client handle
 * - `account_id_hex`: Account ID (hex string)
 * - `callback`: Callback function (user_data, error_code, json_ptr, json_len)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account ID parsing failed
 */
int32_t wc_miden_get_balance_async(MidenHandle handle,
                                   const char *account_id_hex,
                                   GetBalanceCallback callback,
                                   void *user_data);

/**
 * Get consumable Input Notes
 *
 * Returns all consumable notes (unspent, committed notes).
 *
 * # Parameters
 * - `handle`: Client handle
 * - `account_id_hex`: Account ID (hex string, can be NULL to get notes for all accounts)
 * - `notes_json_out`: Output buffer for JSON-formatted notes list
 * - `notes_json_out_len`: Input as buffer size, output as actual length
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account ID parsing failed
 * - -4: Get failed
 *
 * # JSON 输出格式
 * ```json
 * {
 *   "notes": [
 *     {
 *       "note_id": "0x...",
 *       "assets": [{"faucet_id": "0x...", "amount": 1000}],
 *       "is_authenticated": true
 *     }
 *   ],
 *   "total_count": 1
 * }
 * ```
 */
int32_t wc_miden_get_input_notes(MidenHandle handle,
                                 const char *account_id_hex,
                                 uint8_t *notes_json_out,
                                 uintptr_t *notes_json_out_len);

/**
 * Async version of get input notes
 *
 * # Parameters
 * - `handle`: Client handle
 * - `account_id_hex`: Account ID (hex string, can be NULL for all accounts)
 * - `callback`: Callback function (user_data, error_code, json_ptr, json_len)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account ID parsing failed
 */
int32_t wc_miden_get_input_notes_async(MidenHandle handle,
                                       const char *account_id_hex,
                                       GetInputNotesCallback callback,
                                       void *user_data);

/**
 * Consume Notes
 *
 * Create and submit a transaction to consume specified notes.
 *
 * # Parameters
 * - `handle`: Client handle
 * - `account_id_hex`: Account ID to execute transaction (hex string)
 * - `note_ids_json`: JSON-formatted array of note IDs (e.g., `["0x...", "0x..."]`)
 * - `tx_id_out`: Output buffer for transaction ID (at least 64 bytes)
 * - `tx_id_out_len`: Input as buffer size, output as actual length
 *
 * # Returns
 * - 0: Success
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account ID parsing failed
 * - -4: Note IDs parsing failed
 * - -5: Transaction creation failed
 * - -6: Transaction submission failed
 */
int32_t wc_miden_consume_notes(MidenHandle handle,
                               const char *account_id_hex,
                               const char *note_ids_json,
                               uint8_t *tx_id_out,
                               uintptr_t *tx_id_out_len);

/**
 * Async version of consume notes
 *
 * # Parameters
 * - `handle`: Client handle
 * - `account_id_hex`: Account ID to execute transaction (hex string)
 * - `note_ids_json`: JSON-formatted array of note IDs
 * - `callback`: Callback function (user_data, error_code, tx_id_ptr, tx_id_len)
 * - `user_data`: User data passed to callback
 *
 * # Returns
 * - 0: Task started successfully
 * - -1: Invalid parameters
 * - -2: Invalid handle
 * - -3: Account ID parsing failed
 * - -4: Note IDs parsing failed
 */
int32_t wc_miden_consume_notes_async(MidenHandle handle,
                                     const char *account_id_hex,
                                     const char *note_ids_json,
                                     ConsumeNotesCallback callback,
                                     void *user_data);

int32_t wc_keccak256(const uint8_t *data_ptr,
                     uintptr_t data_len,
                     uint8_t *out_ptr,
                     uintptr_t *out_len);

/**
 * Convert account ID to hex string
 */
int32_t wc_miden_account_id_to_hex(const uint8_t *account_id_ptr,
                                   uintptr_t account_id_len,
                                   uint8_t *hex_out,
                                   uintptr_t *hex_out_len);

#endif  /* MIDEN_SWIFT_CLIENT_H */
